### ISSUE TITLE
uploads directory is absent in the repo

### ISSUE THREAD

**Issue by sudarshansb143** [ahmetkkn07/OMR#1]
while uploading the files the error is thrown saying that  the uploads directory is absent at the location 'static/upload' 
![image](https://user-images.githubusercontent.com/43947282/100425724-b8a58080-30b5-11eb-9945-4d33f7f94332.png) maybe its like creating the directory after running server.py but due to several permission issues I think the uploads directory should be provided.

**Comment by ahmetkkn07** [comment]
You can download project from releases. Upload directory is provided there. I will add them to repo, thanks.

**Comment by ahmetkkn07** [comment]
Added directory to repo
